services:
    - type: Proxy
      url: github.com/ahmetson/today-do/list-local
      id: list-proxy
      manager:
        url: github.com/ahmetson/today-do/list-local
        id: list-proxy_manager
        port: 58563
        zmq_type: 4
      handlers:
        - type: SyncReplier
          category: list-proxymain
          instance_amount: 1
          port: 58564
          id: list-proxymain_1
      sources:
        - proxies:
            - proxy:
                local:
                    local_bin: ..\proxy\bin\test.exe
                id: web-proxy
                url: github.com/ahmetson/web-proxy
                category: entry
              manager:
                url: github.com/ahmetson/web-proxy
                id: web-proxy_manager
                port: 54362
                zmq_type: 4
              clients:
                - url: github.com/ahmetson/web-proxy
                  id: web-proxymain_1
                  port: 54363
                  zmq_type: 6
                - url: github.com/ahmetson/web-proxy
                  id: web-proxylist-proxymain_1
                  port: 58569
                  zmq_type: 6
          rule:
            urls:
                - github.com/ahmetson/today-do
            categories: []
            commands: []
            excluded_commands: []
proxy_chains: []
