services:
    - type: Independent
      url: github.com/ahmetson/today-do
      id: todaydo
      manager:
        url: ""
        id: manager_1
        port: 57397
        zmq_type: 4
      handlers:
        - type: SyncReplier
          category: main
          instance_amount: 1
          port: 57398
          id: main_1
      proxies: []
      extensions: []
      proxy_order: []
    - type: Independent
      url: github.com/ahmetson/today-do/proxy
      id: web
      manager:
        url: ""
        id: manager_1
        port: 2096
        zmq_type: 4
      handlers:
        - type: SyncReplier
          category: main
          instance_amount: 1
          port: 2097
          id: main_1
        - type: Replier
          category: entry
          instance_amount: 1
          port: 2626
          id: entry_1
      proxies: []
      extensions: []
      proxy_ order: []
