services:
    - type: Independent
      url: github.com/ahmetson/today-do
      id: todaydo
      manager:
        url: github.com/ahmetson/today-do
        id: todaydo_manager
        port: 54222
        zmq_type: 4
      handlers:
        - type: SyncReplier
          category: main
          instance_amount: 1
          port: 54223
          id: main_1
      sources:
        - proxies:
            - proxy:
                local:
                    local_bin: ..\proxy\bin\test.exe
                id: web-proxy
                url: github.com/ahmetson/web-proxy
                category: entry
              manager:
                url: github.com/ahmetson/web-proxy
                id: web-proxy_manager
                port: 54362
                zmq_type: 4
              clients:
                - url: github.com/ahmetson/web-proxy
                  id: web-proxymain_1
                  port: 54363
                  zmq_type: 6
            - proxy:
                local:
                    local_bin: ..\list-proxy\bin\test.exe
                id: list-proxy
                url: github.com/ahmetson/today-do/list-local
                category: convert
              manager:
                url: github.com/ahmetson/today-do/list-local
                id: list-proxy_manager
                port: 58563
                zmq_type: 4
              clients:
                - url: github.com/ahmetson/today-do/list-local
                  id: list-proxymain_1
                  port: 58564
                  zmq_type: 4
          rule:
            urls:
                - github.com/ahmetson/today-do
            categories: []
            commands: []
            excluded_commands: []
proxy_chains: []
