services:
    - type: Independent
      url: github.com/ahmetson/today-do
      id: todaydo
      manager:
        serviceurl: github.com/ahmetson/today-do
        id: manager_1
        port: 57397
        targettype: 4
      handlers:
        - type: SyncReplier
          category: main
          instanceamount: 1
          port: 57398
          id: main_1
      proxies: []
      extensions: []
      proxyorder: []
    - type: Independent
      url: github.com/ahmetson/today-do/proxy
      id: web
      manager:
        serviceurl: ""
        id: manager_1
        port: 2096
        targettype: 0
      handlers:
        - type: SyncReplier
          category: main
          instanceamount: 1
          port: 2097
          id: main_1
        - type: Replier
          category: entry
          instanceamount: 1
          port: 2626
          id: entry_1
      proxies: []
      extensions: []
      proxyorder: []
